In [49]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [8]:
diab_dtst = pd.read_csv("diabetes.csv")

In [9]:
pd.read_csv?

In [11]:
diab_dtst.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [13]:
diab_dtst.shape

(2460, 9)

In [15]:
diab_dtst.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000
mean,3.817480,121.602033,68.915041,20.531301,80.119919,31.990447,0.491440,32.821951,0.390244
std,3.296458,31.789270,19.082655,15.716901,116.765807,7.802569,0.363917,11.251208,0.487904
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,100.000000,64.000000,0.000000,0.000000,27.100000,0.251750,24.000000,0.000000
50%,3.000000,117.000000,70.000000,23.000000,36.000000,32.100000,0.381000,29.000000,0.000000
75%,6.000000,142.000000,80.000000,33.000000,129.000000,36.500000,0.647000,39.000000,1.000000
max,17.000000,197.000000,122.000000,63.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [20]:
diab_dtst["Outcome"].value_counts()

Outcome
0    1500
1     960
Name: count, dtype: int64

In [24]:
diab_dtst.groupby("Outcome").mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.242000,110.413333,67.852667,19.637333,69.938000,30.066133,0.444710,30.866000
1,4.716667,139.084375,70.575000,21.928125,96.029167,34.997188,0.564455,35.878125

In [25]:
X = diab_dtst.drop(columns = "Outcome", axis = 1)
Y = diab_dtst["Outcome"]

In [27]:
print(X)

      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               6      148             72             35        0  33.6
1               1       85             66             29        0  26.6
2               8      183             64              0        0  23.3
3               1       89             66             23       94  28.1
4               0      137             40             35      168  43.1
...           ...      ...            ...            ...      ...   ...
2455            3      126             88             41      235  39.3
2456            4      123             62              0        0  32.0
2457            1       80             74             11       60  30.0
2458            1       96             64             27       87  33.2
2459            6      105             70             32       68  30.8

      DiabetesPedigreeFunction  Age
0                        0.627   50
1                        0.351   31
2                        0.672   32
3                        0.167   21
4                        2.288   33
...                        ...  ...
2455                     0.704   27
2456                     0.226   35
2457                     0.527   22
2458                     0.289   21
2459                     0.122   37

[2460 rows x 8 columns]

In [29]:
print(Y)

0       1
1       0
2       1
3       0
4       1
       ..
2455    0
2456    1
2457    0
2458    0
2459    0
Name: Outcome, Length: 2460, dtype: int64

In [31]:
scalar = StandardScaler()

In [32]:
scalar.fit(X)

StandardScaler()

In [34]:
standard_dt = scalar.transform(X)

In [36]:
print(standard_dt)

[[ 0.66221514  0.83057379  0.16169587 ...  0.20632694  0.3725791
   1.52708417]
 [-0.854873   -1.1516299  -0.15278971 ... -0.69099593 -0.3859906
  -0.16196676]
 [ 1.26905039  1.93179806 -0.25761824 ... -1.11401957  0.49625894
  -0.07306934]
 ...
 [-0.854873   -1.30894766  0.2665244  ... -0.25515339  0.09773501
  -0.96204351]
 [-0.854873   -0.80553085 -0.25761824 ...  0.15505135 -0.55639394
  -1.05094093]
 [ 0.66221514 -0.52235889  0.05686735 ... -0.15260221 -1.01538357
   0.37141775]]

In [37]:
X = standard_dt

In [39]:
Y = diab_dtst["Outcome"]

In [43]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify = Y, random_state = 2)

In [45]:
print(X.shape, X_train.shape, X_test.shape)

(2460, 8) (1968, 8) (492, 8)

In [46]:
classifier = svm.SVC(kernel = "linear")

In [47]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [50]:
X_train_predict = classifier.predict(X_train)
train_dt_acc = accuracy_score(X_train_predict, Y_train)

In [53]:
print(f"The accuracy of training data: {train_dt_acc}")

The accuracy of training data: 0.7367886178861789

In [54]:
X_test_predict = classifier.predict(X_test)
test_dt_acc = accuracy_score(X_test_predict, Y_test)

In [56]:
print(f"The accuracy of test data: {test_dt_acc}")

The accuracy of test data: 0.7540650406504065

In [59]:
inp_data = (4, 110, 92, 0, 0, 37.6, 0.191, 30)
inp_np_arr = np.asarray(inp_data)
inp_rsp = inp_np_arr.reshape(1,-1)

stan_dt = scalar.transform(inp_rsp)
print(stan_dt)

predict = classifier.predict(stan_dt)
# print(predict)

if predict[0] == 0:
  print("The person is non diabetic")
else:
  print("The person is diabetic")

[[ 0.05537988 -0.36504114  1.20998115 -1.3065855  -0.68629859  0.71908287
  -0.82574115 -0.25086418]]
The person is non diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(